require (bitops)
require (dplyr)
require (ggplot2)
require (grid)
require (jsonlite)
require (knitr)
require (markdown)
require (plyr)
require (RCurl)
require (reshape2)
require (rmarkdown)
require(shiny)
require (stringr)
require (tidyr)
